# [--snakefile FILE] 
#cores: 64
# [--local-cores N] 


# [--directory DIR] 
#keep-going: true 
rerun-incomplete: true
# [--shadow-prefix DIR] 
# [--reason] 
# [--latency-wait SECONDS] 
# [--max-jobs-per-second MAX_JOBS_PER_SECOND] 
# [--greediness GREEDINESS] 
# [--runtime-profile FILE] 
show-failed-logs: true
drmaa: "
    --mem={cluster.mem}
    --cpus-per-task={cluster.cpus-per-task} 
    --time={cluster.time} 
    --account={cluster.account}
    --error={cluster.error} 
    --output={cluster.output}
"

cluster-config: "config/slurm/cluster.yaml" 


# [--jobscript SCRIPT] 
jobname: "{name}.{jobid}.snakejob.sh" 
use-conda: true
#use-singularity: true
# [--conda-prefix DIR] 

default-resources: 
  - walltime="1:00:00"
  - mem_mb=4096
printshellcmds: True

keep-going: true 
#rerun-incomplete: true
#restart-times: 1
max-jobs-per-second: "0.01"
max-status-checks-per-second: 1
latency-wait: 120
